### ISSUE TITLE
[ Fix ] v1 구글 플레이 출시 전 최종 수정

### ISSUE THREAD

**Issue by sillonjeu** [9oormthon-univ/2024_BEOTKKOTTHON_TEAM_9_FE#81]
## 🛠 Issue

v1 구글 플레이 출시 전 최종 수정

## 📝 To-do

- [x] 카카오 SNS 로그인 연동 및 자동 회원가입 정보 기입
- [x] 회원가입 폼 수정
- [x] 좋아요 로직 수정
- [x] 채팅(로그 전체 겹침 현상, 로그 사용자/강아지 분리 안되는 현상, 랜덤 채팅 안되는 현상, 로그에서 채팅으로 들어가기) 수정
- [x] 마이페이지 한국어 깨짐 수정
- [x] 자잘한 디자인(로그인, 회원가입, 채팅) 수정
